[files]
currents = "../../weather_data/sept-ile-grande-entree/currents.nc"
atmo = "../../weather_data/sept-ile-grande-entree/atmo.nc"
sun = "../../weather_data/sept-ile-grande-entree/sun.nc"

[variants.may01.files]
currents = "../../weather_data/sept-ile-grande-entree/currents.nc"
atmo = "../../weather_data/sept-ile-grande-entree/atmo.nc"
sun = "../../weather_data/sept-ile-grande-entree/sun.nc"

[variants.jun01.files]
currents = "../../weather_data/sept-ile-grande-entree/currents.nc"
atmo = "../../weather_data/sept-ile-grande-entree/atmo.nc"
sun = "../../weather_data/sept-ile-grande-entree/sun.nc"

[variants.jun28.files]
currents = "../../weather_data/sept-ile-grande-entree/currents.nc"
atmo = "../../weather_data/sept-ile-grande-entree/atmo.nc"
sun = "../../weather_data/sept-ile-grande-entree/sun.nc"
