[files]
currents = "../../weather_data/halifax-grande-entree/currents_hal_ge.nc"
atmo = "../../weather_data/halifax-grande-entree/atmo_hal_ge.nc"
sun = "../../weather_data/halifax-grande-entree/sun_hal_ge.nc"
